name: Docker Image CI


on:
  push:
    paths:
    - '**/ansible/Dockerfile'

env:
  REGISTRY: docker.pkg.github.com

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: ENV
      run: env 
 
    - name: Login to github docker registry 
      run: docker login $REGISTRY  -u ${{ secrets.USERNAME }} -p ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file ansible/Dockerfile --tag $REGISTRY/$GITHUB_REPOSITORY_OWNER/operator-sdk-dev:ansible

    - name: Push image
      run: docker push $REGISTRY/$GITHUB_REPOSITORY_OWNER/operator-sdk-dev:ansible


