name: Docker Image CI


on:
  push:
    paths:
    - '**/ansible/Dockerfile'


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to github docker registry 
      run: echo  -n $GITHUB_TOKEN |  docker login ${{ secrets.REGISTRY }}  -u ${{ secrets.USERNAME }} --password-stdin

    - name: Build the Docker image
      run: docker build . --file ansible/Dockerfile --tag docker.pkg.github.com/$GITHUB_REPOSITORY_OWNER/operator-sdk-dev:ansible

