name: Docker Image CI


on:
  push:
    paths:
    - '**/ansible/Dockerfile'


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check docker engine 
      run: docker info 

    - name: Check ENV variables
      run: env
    - name: Build the Docker image
      run: docker build . --file ansible/Dockerfile --tag operator-sdk-dev:ansible

